### ISSUE TITLE
Unable to enable Citador since recent update

### ISSUE THREAD

**Issue by Favna** [nirewen/Citador#85]
**Note: This is likely going to be the same issue to resolve as reported to Samogot's quoter [here](https://github.com/samogot/betterdiscord-plugins/issues/39) as they have nigh matching errors**

```
Citador version: 3.7.13
BD v0.2.82
BBD v0.1.0 (Zerebos)
```

Enabling Citador fails entirely and the following error is thrown in the console:

```sh
Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at Object.t.toString (https://discordapp.com/assets/feec13af5e884a173f6a.js:62:104285)
    at https://rauenzi.github.io/BetterDiscordAddons/Plugins/PluginLibrary.js?v=2:1002:17
    at Object.find (https://rauenzi.github.io/BetterDiscordAddons/Plugins/PluginLibrary.js?v=2:923:14)
    at Citador.patchExternalLinks (<anonymous>:409:58)
    at Citador.initialize (<anonymous>:95:10)
    at Citador.start (<anonymous>:48:12)
    at PluginModule.startPlugin (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/e4940b320c815227ccd98228eb66f6b1ebb48c3d/js/main.min.js:52:18650)
    at PluginModule.enablePlugin (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/e4940b320c815227ccd98228eb66f6b1ebb48c3d/js/main.min.js:52:19266)
    at PluginModule.togglePlugin (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/e4940b320c815227ccd98228eb66f6b1ebb48c3d/js/main.min.js:52:19483)
    at V2C_PluginCard.onChange (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/e4940b320c815227ccd98228eb66f6b1ebb48c3d/js/main.min.js:52:48310)
    at Object.<anonymous> (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:686)
    at Object.invokeGuardedCallback (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:753)
    at Object.invokeGuardedCallbackAndCatchFirstError (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:868)
    at N (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:2324)
    at D (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:2803)
    at P (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:2960)
    at Array.forEach (native)
    at R (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:2593)
    at U (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:3565)
    at F (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:3721)
    at Nn (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:30947)
    at Zo (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:85592)
    at Xe (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:12586)
    at Pn (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:31495)
    at ns (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:85895)
    at Ln (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:31238)
    at HTMLDocument.a (https://discordapp.com/assets/feec13af5e884a173f6a.js:62:793656)
```

Furthermore disabling Citador throws:

```sh
[BetterDiscord] Plugin  could not be stopped.
main.min.js:52 Error: this.cancel is not a function
feec13a….js:119 TypeError: this.cancel is not a function
    at Citador.deleteEverything (<anonymous>:526:10)
    at Citador.stop (<anonymous>:29:29)
    at PluginModule.stopPlugin (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/e4940b320c815227ccd98228eb66f6b1ebb48c3d/js/main.min.js:52:18967)
    at PluginModule.disablePlugin (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/e4940b320c815227ccd98228eb66f6b1ebb48c3d/js/main.min.js:52:19377)
    at PluginModule.togglePlugin (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/e4940b320c815227ccd98228eb66f6b1ebb48c3d/js/main.min.js:52:19461)
    at V2C_PluginCard.onChange (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/e4940b320c815227ccd98228eb66f6b1ebb48c3d/js/main.min.js:52:48310)
    at Object.<anonymous> (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:686)
    at Object.invokeGuardedCallback (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:753)
    at Object.invokeGuardedCallbackAndCatchFirstError (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:868)
    at N (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:2324)
    at D (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:2803)
    at P (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:2960)
    at Array.forEach (native)
    at R (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:2593)
    at U (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:3565)
    at F (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:3721)
    at Nn (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:30947)
    at Zo (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:85592)
    at Xe (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:12586)
    at Pn (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:31495)
    at ns (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:85895)
    at Ln (https://discordapp.com/assets/feec13af5e884a173f6a.js:101:31238)
    at HTMLDocument.a (https://discordapp.com/assets/feec13af5e884a173f6a.js:62:793656)
```

**Comment by Rainezi** [comment]
I can enable it but, it doesn't work, the quote button doesn't appear anymore, this started today.

**Comment by HYPExMon5ter** [comment]
^ same for me.

**Comment by nirewen** [comment]
Thank you very much for reporting! This will be fixed in a minute
